### ISSUE TITLE
Error: Cannot find module 'nopt'

### ISSUE THREAD

**Issue by ashwinncj** [45air/air-local-docker#3]
I am trying to install airlocal on Ubuntu 20.04 and the command `npm install @45air/air-local-docker` always fails with 

```
Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/nodejs/node-gyp/lib/node-gyp.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++` ```

I tried `sudo apt-get install g++ build-essential` but it doesn't help. How can I fix this issue and install Airlocal?

**Comment by ashwinncj** [comment]
I tried `sudo apt-get install g++ build-essential` but it doesn't help. How can I fix this issue and install Airlocal?

**Comment by ashwinncj** [comment]
Solved the issue. It was related to the `npm` and `fibers`. The latest version of `fibers` requires `npm 12 and above`. Used `nvm` to update the node version and fixed the issue.
